Full Rewrite with Linux and (theoretically) MacOS Support
JordanZeotni/BotW-Save-Manager pull request #17
Opened 2022-11-02 09:45 UTC by ArchLeaders

I was bored, and I thought this was a cool tool that could be improved. So I rewrote it using AvaloniaUI (cross-platform UI framework) and .NET 6. It reflects the WinForms version, but with some QoL improvements like drag/drop and quick convert options.

### Changelog:

- Cross-platform support for the UI and Console applications (workflows only build for Windows/Linux, macOS _should_ also be supported though)
- DotNET 6 and C# 10 features and performance
- General UI/UX improvement
  - Dark theme (light theme is also supported, but not implemented)
  - Quicker save convert menu item `File > Convert Save`
  - Folder drag/drop support
  - Built-in async logs viewer
- Refactored save converter (Switch saves for BOTW v1.6 were not tested)
- Improved logging
- Clarified documentation (ReadMe)
- GitHub publishing workflows (trigger with `git tag vX.Y.X && git push --tags`)
  - Single file deployment

### To-do:

- Browse for `option.sav` to narrow down selection and prevent user errors.
  - Currently waiting for _me_ to update my Avalonia File Browser extension to support filtering.

2022-11-17 20:50 UTC, DeltaJordan commented
Thank you for this. I originally wrote this when I was a lot less experienced than I am now haha, but this is really nicely done. I'll give the code a quick review and approve this if everything checks out.

2022-11-17 21:10 UTC, DeltaJordan requested changes

2022-11-17 21:10 UTC, DeltaJordan commented on BotwSaveManager.Core/Helpers/Logger.cs
> +        private static readonly string SourceRoot = "F:\\GitHub\\BotwSaveManager";
Don't use hard-coded paths. If you want to have a logger, use `AppDomain.CurrentDomain.BaseDirectory` to get the current application path, then add a folder for logging.

2022-11-17 21:10 UTC, DeltaJordan commented on BotwSaveManager.Console/Program.cs
> +Console.WriteLine("Breath of the Wild Save Manager by Jordan Zeotni, fork of https://github.com/WemI0/BOTW_SaveConv, rewritten and updated by Arch Leaders\n\n");
Update "Jordan Zeotni" to "Jordan Marine" I used to use a fake last name back in 2020. That's my fault.

2022-11-17 21:10 UTC, DeltaJordan commented on BotwSaveManager/Resource.cs
> +            if (File.Exists($"{root}/{name}")) {
When combining paths in cross-platform applications, it is better to use `Path.Combine` then to concatenate two paths, as there are a few (uncommon) cases where putting a slash between two paths causes issues.

2022-11-17 21:10 UTC, DeltaJordan commented on README.md
> +3. Wait once more for the completion message.
Well written description, thanks.

2022-11-17 23:44 UTC, ArchLeaders commented on BotwSaveManager.Core/Helpers/Logger.cs
> +        private static readonly string SourceRoot = "F:\\GitHub\\BotwSaveManager";
This isn't the log outputs folder, it's the path to the source code to shorten the source file paths in the logs. (See [Line 29](https://github.com/DeltaJordan/BotW-Save-Manager/pull/17/files/b42c572cab8c3248be4f15dacae35e4c4dd2450d#diff-0e86ff6cb991092e11c8571f90c4e383ea824b1817e647f04dcd66f113bb357dR29))
However, I may need to change it to reflect the workflow path, as I only tested this when building on my machine (and therefore my source code path).

2022-11-19 01:46 UTC, DeltaJordan approved these changes

2022-11-19 01:46 UTC, merged